### PR TITLE
Uncaught TypeError: Cannot read property 'concat' of null

### PR DESCRIPTION
**Pull request by abe33**
1. Open a sass file
2. Starts writing a class selector by typing a `.` or an id selector by typing a `#`

**Atom Version**: 1.0.4-54f6ed8
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-css](https://github.com/atom/autocomplete-css) package, v0.10.0
### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35

TypeError: Cannot read property 'concat' of null
    at Object.module.exports.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35:79)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -1:15.3.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
  2x -1:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:12.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.2.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:45.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:31.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:29.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:25.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:25.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:25.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:25.2.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "coffee-lint",
      "emmet",
      "notebook",
      "rsense",
      "font-viewer",
      "react-minimap",
      "sample-minimap-plugin",
      "term2",
      "color-picker",
      "crosshairs",
      "enhanced-package-list",
      "themed-settings",
      "project-palette-finder",
      "atom-color-highlight",
      "view-tail-large-files",
      "minimap-color-highlight",
      "to-base64"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-dark-syntax"
    ],
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.0.0
about, v1.0.1
bezier-curve-editor, v0.7.2
block-travel, v1.0.2
bug-report, v0.7.1
figlet, v0.4.0
file-icons, v1.5.8
highlight-selected, v0.10.1
language-generic-config, v0.2.0
language-haml, v0.21.0
language-jade, v0.6.2
language-sass, v0.40.0
minimap, v4.12.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.2
minimap-selection, v4.3.0
php-twig, v4.0.0
pigments, v0.9.2
project-manager, v1.15.11
red-wavy-underline, v0.3.0
spacegray-dark-syntax, v0.2.0
tabs-to-spaces, v0.11.0
travis-ci-status, v0.16.0
tree-view-breadcrumb, v0.6.1
tree-view-open-files, v0.2.4
typewriter, v0.3.3
white-cursor, v0.6.0
zentabs, v0.8.4

# Dev
minimap, v4.12.1
pigments, v0.9.1
```

### CODE REVIEW

**Comment by abe33** [comment]
Looks like it's also triggered when I type a comma after a selector, but only if the line is indented.

**Comment by benogle** [comment]
Thanks for this!

**Comment by D-side** [comment]
Just encountered the same. **Sass** too. When typing this:

``` sass
time
  $imprint-color: mix($theme0C, $theme05)
  $accent-color: $theme0
```

Once I type the last zero, this error pops up. At least Atom claims it's the same as in this PR.

**Atom Version**: 1.0.7
**System**: Linux Mint 17.1 XFCE
**Thrown From**: [autocomplete-css](https://github.com/atom/autocomplete-css) package, v0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of null

```
At /opt/atom/resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35

TypeError: Cannot read property 'concat' of null
    at Object.module.exports.getSuggestions (/opt/atom/resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35:65)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
    at /opt/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -1:49.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.autocomplete-active.is-focused)
  3x -1:49.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:44.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:43 editor:newline (atom-text-editor.editor.is-focused)
     -1:41.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:41.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:41.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:36.9.0 editor:move-line-down (atom-text-editor.editor.is-focused)
  2x -0:27.2.0 core:cancel (a.stack-toggle)
     -0:23.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:23.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:03.2.0 core:move-left (atom-text-editor.editor.autocomplete-active.is-focused)
     -0:02.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:02.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "tomorrow-night-eighties-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-material-ui, v0.5.20
autocomplete-clang, v0.8.7
browser-plus, v0.0.34
color-picker, v2.0.11
file-icons, v1.6.3
linter, v1.3.4
minimap, v4.12.3
pigments, v0.11.0
tomorrow-night-eighties-syntax, v0.6.1

# Dev
No dev packages
```

**Comment by ghost** [comment]
[Enter steps to reproduce below:]
1. Also just got this Error. Got it when I used media querie with max-width and width in pixel

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-css](https://github.com/atom/autocomplete-css) package, v0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'concat' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35

TypeError: Cannot read property 'concat' of null
    at Object.module.exports.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35:65)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:16.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:16.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:12.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:12.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:11.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:10.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:09.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:09.4.0 core:move-up (atom-text-editor.editor.is-focused)
  8x -0:08.4.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  5x -0:06.6.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:03.7.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:02.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:01.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:01.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "audioBeep": false,
    "projectHome": "/Users/mdanek/Development/",
    "ignoredNames": [
      ".DS_Store",
      ".css.map",
      ".map",
      ".git",
      ".sass-cache"
    ],
    "disabledPackages": [
      "wrap-guide"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
language-typoscript2, v0.2.0
minimap, v4.13.1
typo3-fluid-atom-snippets, v1.2.0

# Dev
No dev packages
```

**Comment by jstiger** [comment]
Same with:
.crmLanding{
  h1{
    font-size:4.4rem;
    color:#305386;
    .lightBlue{
      color:#46ade3;
    }
  }
  h2{
    24 px
  }
}

**Comment by alex88** [comment]
Same here with the media queries!

**Comment by marcboeker** [comment]
I've experienced the issue with flexbox's `order` property.

**Comment by MentalGear** [comment]
Error appears when typing animaton-delay, or animation-name.

/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35
Hide Stack Trace
TypeError: Cannot read property 'concat' of null
  at Object.module.exports.getSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-css/lib/provider.js:35:65)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

**Comment by winstliu** [comment]
This is awkward because the issue was changed into a PR and as such I can't reopen it...
@abe33 want to take another look at this?

**Comment by benogle** [comment]
I've pushed a fix so this shouldnt happen anymore. No need to reopen things.

**Pull request merged**
