### PR TITLE
Update completions.json

### PR DESCRIPTION
**Pull request by Ollie-w**
Added CSS grid properties.

### CODE REVIEW

**Comment by winstliu** [comment]
This file is autogenerated, so any manual changes (such as this one) will be deleted when the update process is run.  Please submit these changes upstream, and then they'll eventually trickle down to here.

**Comment by Ollie-w** [comment]
Hi 50Wliu. Excuse my ignorance. Where about's should the code be added to?

**Comment by winstliu** [comment]
I believe they are sourced from https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json.

**Comment by Ollie-w** [comment]
I don't understand why Atom is using Brackets code. They don't seem to be willing to update their css properties. This is driving me nuts. My text editor feels unusable :(

**Comment by winstliu** [comment]
If you can find a better list, or have compelling arguments as to why we should do it ourselves, feel free to open a new issue :).

**Comment by Ollie-w** [comment]
I added the properties to Brackets and my changes have now been merged. How long does it take for Atom to take note of those changes?

**Comment by winstliu** [comment]
I just re-ran the `update.coffee` file, but it looks like some of the new property names (such as `grid-area`) aren't included in `sorted-property-names.json` and as such are being excluded from the final completions list.

/cc @benogle: how is `sorted-property-names.json` supposed to be updated?  Here's what I'm seeing right now:

```
Ignoring font-display; not in sorted-property-names.json
Ignoring grid; not in sorted-property-names.json
Ignoring grid-area; not in sorted-property-names.json
Ignoring grid-column-gap; not in sorted-property-names.json
Ignoring grid-gap; not in sorted-property-names.json
Ignoring grid-row-gap; not in sorted-property-names.json
Ignoring grid-template-areas; not in sorted-property-names.json
```

**Comment by winstliu** [comment]
Sorry for the delay @Ollie-w - the new completions are now on master and should be available starting in Atom 1.13.0.

**Pull request closed without merging**
